"""Profile slot helpers and distribution templates (v2)."""

from __future__ import annotations

import os
import shutil
from pathlib import Path
from typing import Iterable

from hca.config import PACKAGE_DIR, FleetConfig

ROLE_TEMPLATES = {
    "orchestrator": "orchestrator",
    "coder": "coder-worker",
    "research": "research-worker",
    "qa": "qa-worker",
    "creative": "creative-worker",
}


def profiles_src_dir() -> Path:
    return PACKAGE_DIR / "templates" / "profiles"


def hermes_profiles_root() -> Path:
    return Path(os.path.expanduser("~/.hermes/profiles"))


def slot_profile_name(fleet: str, role: str, index: int) -> str:
    # Hermes profile directory name; keep simple
    return f"hca-{fleet}-{role}-{index:02d}"


def iter_slot_profiles(cfg: FleetConfig) -> Iterable[tuple[str, str, int, str]]:
    """yield role, template_dir_name, index, profile_name"""
    for role, count in cfg.profile_slots.items():
        tmpl = ROLE_TEMPLATES.get(role, f"{role}-worker")
        for i in range(1, int(count) + 1):
            yield role, tmpl, i, slot_profile_name(cfg.name, role, i)


def render_profile_config(
    *,
    model: str,
    endpoint: str,
    max_children: int = 2,
    context_length: int = 65536,
) -> str:
    # Keys follow the documented Hermes config.yaml schema:
    # https://hermes-agent.nousresearch.com/docs/user-guide/configuration
    # Self-hosted OpenAI-compatible endpoints use provider `custom`; Hermes
    # requires >=64k context for agent/tool use.
    return f"""# Generated by hca init — model must match backend /v1/models id
model:
  provider: custom
  default: {model}
  base_url: {endpoint}
  api_key: local
  api_mode: chat_completions
  context_length: {context_length}

agent:
  max_turns: 500
  api_max_retries: 5
  tool_use_enforcement: auto

compression:
  enabled: true
  threshold: 0.50
  target_ratio: 0.20
  protect_last_n: 20

delegation:
  max_concurrent_children: {max_children}
  max_spawn_depth: 1
  orchestrator_enabled: false
  max_iterations: 30

terminal:
  backend: local
  timeout: 300
"""


def init_profiles(cfg: FleetConfig, *, force: bool = False, dry_run: bool = False) -> list[str]:
    src_root = profiles_src_dir()
    dst_root = hermes_profiles_root()
    created = []
    for role, tmpl, index, profile in iter_slot_profiles(cfg):
        dst = dst_root / profile
        src = src_root / tmpl
        if dry_run:
            created.append(str(dst))
            continue
        dst.mkdir(parents=True, exist_ok=True)
        # SOUL.md from template if present
        soul_src = src / "SOUL.md"
        if soul_src.is_file():
            shutil.copy2(soul_src, dst / "SOUL.md")
        cfg_path = dst / "config.yaml"
        if cfg_path.exists() and not force:
            created.append(f"{profile} (config preserved)")
            continue
        if cfg_path.exists() and force:
            bak = dst / f"config.yaml.bak.{int(__import__('time').time())}"
            shutil.copy2(cfg_path, bak)
        cfg_path.write_text(
            render_profile_config(
                model=cfg.backend.model or "local-model",
                endpoint=cfg.backend.endpoint,
                max_children=cfg.delegation_max_children,
            ),
            encoding="utf-8",
        )
        created.append(profile)
    return created
