"""Machine-readable public support claims and generated documentation."""

from __future__ import annotations

from typing import Any

from hca.hermes_compat import KNOWN_STABLE_VERSIONS

SUPPORT_SCHEMA_VERSION = 1
PROJECT_PROVENANCE = "r0b0tlab/hermes-concurrent-agents"


def support_matrix() -> dict[str, Any]:
    """Return the release support matrix consumed by tests and documentation."""
    stable = sorted(KNOWN_STABLE_VERSIONS, key=lambda value: (value.startswith("20"), value))
    return {
        "schema_version": SUPPORT_SCHEMA_VERSION,
        "project": PROJECT_PROVENANCE,
        "stable_hermes_versions": stable,
        "platforms": [
            (
                "Linux / Python 3.11–3.12",
                "Supported",
                "Required unit, contract, integration, and clean-wheel CI lanes.",
            ),
            (
                "Single DGX Spark / GB10",
                "Optimized",
                "Core lifecycle and conservative telemetry acceptance run on one GB10.",
            ),
            (
                "macOS",
                "Portable CI",
                "Portable control-plane smoke only; no GB10/device acceptance claim.",
            ),
        ],
        "capabilities": [
            (
                "Single-host Hermes team orchestration",
                "Supported",
                "Workers, Kanban task truth, and HCA state live on one host.",
            ),
            (
                "Remote model endpoint",
                "Supported",
                "Configured by the selected Hermes profile; HCA does not own credentials or fallback.",
            ),
            (
                "vLLM/SGLang telemetry adapters",
                "Optimized optional",
                "Admission signals only; HCA does not provision or serve models.",
            ),
            (
                "Unknown or unavailable telemetry",
                "Supported conservatively",
                "Never interpreted as unlimited capacity.",
            ),
            (
                "Remote agent placement",
                "Unsupported",
                "No supported remote Kanban claim/heartbeat transport; mutation fails before SSH.",
            ),
        ],
        "evidence": [
            (
                "Deterministic goal-to-result lifecycle",
                "Required",
                "Gated in ordinary CI.",
            ),
            (
                "Pinned stable Hermes private-API contract",
                "Required",
                "Hermes 0.18.2 / 2026.7.7.2, immutable upstream commit verified in CI.",
            ),
            (
                "Latest Hermes main",
                "Advisory",
                "Visible drift signal; not a masked stable-release gate.",
            ),
            (
                "Performance",
                "Workload-bound",
                "No universal worker count or speed claim; measure each model/runtime/profile.",
            ),
        ],
    }


def _table(headers: tuple[str, ...], rows: list[tuple[str, ...]]) -> str:
    lines = [
        "| " + " | ".join(headers) + " |",
        "|" + "|".join("---" for _ in headers) + "|",
    ]
    lines.extend("| " + " | ".join(row) + " |" for row in rows)
    return "\n".join(lines)


def render_support_matrix() -> str:
    """Render the checked-in support matrix deterministically."""
    data = support_matrix()
    versions = ", ".join(f"`{version}`" for version in data["stable_hermes_versions"])
    sections = [
        "<!-- generated by scripts/generate-support-matrix.py; do not edit -->",
        "# Support matrix",
        "",
        "This file is generated from `hca.support`, which is exercised by release tests.",
        "It distinguishes portable core support, optimized telemetry, and unsupported scope.",
        "",
        f"**Verified stable Hermes versions:** {versions}",
        "",
        "## Platforms",
        "",
        _table(("Platform", "Status", "Evidence boundary"), data["platforms"]),
        "",
        "## Capabilities",
        "",
        _table(("Capability", "Status", "Boundary"), data["capabilities"]),
        "",
        "## Release evidence",
        "",
        _table(("Lane", "Gate", "Meaning"), data["evidence"]),
        "",
        "Remote inference is not remote agent placement. A model endpoint may be on another",
        "machine through ordinary Hermes profile configuration, while HCA workers and the",
        "authoritative Kanban board remain colocated.",
        "",
    ]
    return "\n".join(sections)
