"""Package and generated support metadata remain release-truthful."""

from __future__ import annotations

import tomllib
from pathlib import Path

from hca.hermes_compat import KNOWN_STABLE_VERSIONS


ROOT = Path(__file__).resolve().parents[2]


def test_runtime_dependencies_and_modern_license_metadata():
    data = tomllib.loads((ROOT / "pyproject.toml").read_text(encoding="utf-8"))
    build_requires = data["build-system"]["requires"]
    assert any(req.startswith("setuptools>=77") for req in build_requires)
    project = data["project"]
    assert project["license"] == "MIT"
    assert project["license-files"] == ["LICENSE", "NOTICE"]
    assert all(not item.startswith("License ::") for item in project["classifiers"])
    assert project["requires-python"] == ">=3.11,<3.14"
    assert any(req.lower().startswith("pyyaml>=6.0") for req in project["dependencies"])


def test_supported_python_versions_are_mandatory_ci_members():
    workflow = (ROOT / ".github" / "workflows" / "ci.yml").read_text(encoding="utf-8")
    for version in ("3.11", "3.12", "3.13"):
        assert f'"{version}"' in workflow


def test_notices_entry_point_and_sdist_manifest_are_release_complete():
    data = tomllib.loads((ROOT / "pyproject.toml").read_text(encoding="utf-8"))
    assert data["project"]["scripts"]["hca"] == "hca.cli:main"
    assert data["project"]["entry-points"]["hermes_agent.plugins"]["hca"] == "hca.plugin"

    for path in ("LICENSE", "NOTICE", "SECURITY.md", "CHANGELOG.md", "SKILL.md"):
        assert (ROOT / path).is_file()

    notice = (ROOT / "NOTICE").read_text(encoding="utf-8")
    assert "Hermes Agent" in notice and "Nous Research" in notice
    manifest = (ROOT / "MANIFEST.in").read_text(encoding="utf-8")
    for required in ("CHANGELOG.md", "SECURITY.md", "SKILL.md", "docs *.md"):
        assert required in manifest


def test_generated_support_matrix_matches_source_of_truth():
    from hca.support import render_support_matrix

    rendered = render_support_matrix()
    checked_in = (ROOT / "docs" / "support-matrix.md").read_text(encoding="utf-8")
    assert checked_in == rendered
    assert "<!-- generated by scripts/generate-support-matrix.py; do not edit -->" in rendered
    for version in KNOWN_STABLE_VERSIONS:
        assert version in rendered
    assert "Remote agent placement" in rendered
    assert "Unsupported" in rendered
    assert "Remote model endpoint" in rendered
    assert "Supported" in rendered
